#!/usr/bin/env python3
"""Build versioned method guides from GoodMem's maintained SDK documentation.

Usage: python scripts/sdk-refs/generate.py --source /path/to/goodmem [--check]
Reads committed files at versions.json's SHA, never the source worktree.
"""
import argparse
import html
import inspect
import json
import re
import subprocess
from importlib.resources import files
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
REFS = ROOT / "plugins/goodmem/skills/goodmem-sdk/references"
MATRIX = json.loads((HERE / "versions.json").read_text())
LANGUAGES = {"python", "typescript", "java", "dotnet"}


def generate(source):
    if set(MATRIX["packages"]) != LANGUAGES:
        raise ValueError("The supported matrix must contain all four languages")
    commit = MATRIX["source_commit"]
    if not re.fullmatch(r"[0-9a-f]{40}", commit):
        raise ValueError("Pin source_commit to a full commit SHA")

    def read(path):
        return subprocess.check_output(
            ["git", "-C", str(source), "show", f"{commit}:{path}"], text=True)

    manifests = {
        "python": ("clients/python/pyproject.toml", r'^version\s*=\s*"([^"]+)"'),
        "java": ("clients/java/build.gradle.kts", r'^version\s*=\s*"([^"]+)"'),
        "typescript": ("clients/typescript/package.json", r'"version":\s*"([^"]+)"'),
        "dotnet": ("clients/dotnet/VERSION", r"^(\S+)"),
    }
    generated = {}
    for language, package in MATRIX["packages"].items():
        path, pattern = manifests[language]
        match = re.search(pattern, read(path), re.M)
        if not match or match[1] != package["version"]:
            raise ValueError(f"{language}: pinned source and package versions disagree")
        stamp = f'<!-- sdk-ref package={package["package"]} registry={package["registry"]} version={package["version"]} -->'
        intro = (HERE / "templates" / f"{language}.md").read_text().replace("@VERSION@", package["version"])
        provenance = (
            f'<!-- Generated by scripts/sdk-refs/generate.py from GoodMem {commit}. -->\n\n'
            f'This guide supports `{package["package"]}=={package["version"]}`. '
            f'Method contracts come from the [matching GoodMem source](https://github.com/{MATRIX["source_repository"]}/tree/{commit}/clients), '
            'whose package versions are checked during generation. Request models and additional examples are linked by namespace.\n\n'
            '**API-key lifecycle:** `status=INACTIVE` and DELETE both permanently revoke a key. '
            'Revoked keys cannot become ACTIVE; issue a replacement key. There is no separate reversible pause. '
            'Revocation requires `DELETE_API_KEY`, while label edits require `UPDATE_API_KEY`.\n\n')
        sections = []
        if language == "python":
            # The bundled guide has flattened parameters for several methods
            # that actually take request objects. Runtime signatures/docstrings
            # are authoritative, including keyword-only parameters and returns.
            import goodmem
            from goodmem import Goodmem
            if goodmem.__version__ != package["version"]:
                raise ValueError(f'Install goodmem=={package["version"]} before generating')
            body = files("goodmem").joinpath("skills/reference.md").read_text()
            names = re.findall(r"^#### `([\w.]+)\(", body, re.M)
            if len(names) < 40:
                raise ValueError("Published Python namespace catalogue is incomplete")
            sections.append("## API reference\n\nSignatures and descriptions below are inspected from the published Python package. All parameters are keyword-only.\n")
            with Goodmem(base_url="https://example.invalid", api_key="gm_generator_no_network") as client:
                for name in names:
                    method = client
                    for part in name.split("."):
                        method = getattr(method, part)
                    signature = inspect.signature(method)
                    doc = inspect.getdoc(method) or ""
                    # Preserve provider-independent operation semantics, while
                    # omitting duplicated argument types in the docstring.
                    description = doc.split("\nArgs:", 1)[0].split("\nReturns:", 1)[0]
                    sections.append(f"#### `{name}{signature}`\n\n{description}\n")
        else:
            folder = f"docs/website/content/docs/reference/sdk/v2/{language}"
            paths = subprocess.check_output(
                ["git", "-C", str(source), "ls-tree", "-r", "--name-only", commit, folder], text=True).splitlines()
            count = 0
            for path in sorted(paths):
                if not path.endswith(".mdx") or path.endswith("/index.mdx"):
                    continue
                raw = read(path)
                if language == "java":
                    raw = raw.split("## Method Detail\n", 1)[-1]
                    blocks = re.findall(r"(?ms)^### `.*?(?=^### `|^## |\Z)", raw)
                    cutoff = r"\*\*Throws:"
                elif language == "typescript":
                    blocks = re.findall(r"(?ms)^## client\..*?(?=^## |\Z)", raw)
                    cutoff = r"\*\*Example"
                else:
                    blocks = re.findall(r"(?ms)^## \w+Async\b.*?(?=^## |\Z)", raw)
                    cutoff = r"\*\*Exceptions"
                if not blocks:
                    raise ValueError(f"No SDK methods found in {path}; upstream documentation format changed")
                namespace = Path(path).stem
                if language in {"java", "typescript"}:
                    namespace = re.sub(r"_([a-z])", lambda match: match[1].upper(), namespace)
                else:
                    namespace = re.search(r"`client\.([A-Za-z]+)`", raw)[1]
                source_url = f'https://github.com/{MATRIX["source_repository"]}/blob/{commit}/{path}'
                sections.append(f"## client.{namespace}\n\n[Full namespace reference and request models]({source_url})\n")
                for block in blocks:
                    block = re.split(cutoff, block, maxsplit=1)[0].strip()
                    # Remove MDX anchor tags and resolve relative model links to
                    # the exact source page, rather than broken local fragments.
                    block = re.sub(r'<a\s+id="[^"]*"\s*/?>\s*(?:</a>)?', "", block)
                    block = re.sub(r"\]\((?!https?://)([^)]+)\)", lambda m: f"]({source_url}{m[1] if m[1].startswith('#') else ''})", block)
                    block = html.unescape(block)
                    if language == "typescript":
                        # Upstream MDX currently uses Python namespace spelling
                        # in some headings; the published JS accessors are camelCase.
                        block = re.sub(r"client\.([a-z_]+)", lambda match: "client." + re.sub(r"_([a-z])", lambda word: word[1].upper(), match[1]), block)
                    block = block.replace("goodmem-java/latest/", f'goodmem-java/{package["version"]}/')
                    if language != "java":
                        block = re.sub(r"^## ", "### ", block)
                    sections.append(block + "\n")
                    count += 1
            if count < 40:
                raise ValueError(f"Only {count} methods found for {language}; refusing an incomplete guide")
        generated[language] = stamp + "\n" + provenance + intro + "\n\n" + "\n".join(sections).rstrip() + "\n"
    return generated


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for language, text in generate(args.source).items():
        path = REFS / f"{language}.md"
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(text)
        print(f"{language}: {len(text.splitlines())} lines")
    if stale:
        raise SystemExit("Regenerate references: " + ", ".join(stale))


if __name__ == "__main__":
    main()
